# Generated by Django 4.1.4 on 2022-12-30 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(db_column='Пользователь', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='Заголовок', max_length=188)),
                ('text', models.TextField(db_column='Текст')),
                ('photo', models.ImageField(blank=True, db_column='Фото', default='image/default.jpg', null=True, upload_to='image')),
                ('file', models.FileField(blank=True, db_column='Видео/контент', null=True, upload_to='video')),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('PA', 'Танки'), ('HP', 'Хилы'), ('DD', 'ДД'), ('TO', 'Торговцы'), ('GI', 'Гилдмастера'), ('KV', 'Квестгиверы'), ('KU', 'Кузнецы'), ('KO', 'Кожевники'), ('ZE', 'Зельевары'), ('MA', 'Мастера заклинаний')], max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_column='Текст')),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='some.postmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
