# Generated by Django 4.1.4 on 2022-12-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('some', '0002_alter_postmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='category',
            field=models.CharField(choices=[('PA', 'Танки'), ('HP', 'Хилы'), ('DD', 'ДД'), ('TO', 'Торговцы'), ('GI', 'Гилдмастера'), ('KV', 'Квестгиверы'), ('KU', 'Кузнецы'), ('KO', 'Кожевники'), ('ZE', 'Зельевары'), ('MA', 'Мастера заклинаний')], max_length=2),
        ),
    ]
